stops = [
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
    'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his',
    'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself',
    'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which',
    'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are',
    'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having',
    'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if',
    'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for',
    'with', 'about', 'against', 'between', 'into', 'through', 'during',
    'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in',
    'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then',
    'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any',
    'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no',
    'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's',
    't', 'can', 'will', 'just', 'don', 'should', 'now', 'id', 'var',
    'function', 'js', 'd', 'script', '\'script', 'fjs', 'document', 'r',
    'b', 'g', 'e', '\'s', 'c', 'f', 'h', 'l', 'k'
]

# stops = [
#     'un', 'una', 'unas', 'unos', 'uno', 'sobre', 'todo', 'también',
#     'tras', 'otro', 'algún', 'alguno', 'alguna', 'algunos', 'algunas', 'ser',
#     'es', 'soy', 'eres', 'somos', 'sois', 'estoy', 'esta', 'estamos', 'estais',
#     'estan', 'como', 'en', 'para', 'atras', 'porque', 'por qué', 'estado',
#     'estaba', 'ante', 'antes', 'siendo', 'ambos', 'pero', 'por', 'poder',
#     'puede', 'puedo', 'podemos', 'podés', 'pueden', 'fui', 'fue', 'fuimos',
#     'fueron', 'hacer', 'hago', 'hace', 'hacemos', 'haceis', 'hacen', 'cada',
#     'fin', 'incluso', 'primero', 'desde', 'conseguir', 'conseguís', 'consigo',
#     'consigue', 'consigues', 'conseguimos', 'consiguen', 'ir', 'voy', 'va',
#     'vamos', 'vais', 'van', 'vaya', 'bueno', 'ha', 'tener', 'tengo', 'tiene',
#     'tenemos', 'teneis', 'tienen', 'el', 'la', 'lo', 'las', 'los', 'su',
#     'aqui', 'mio', 'tuyo', 'ellos', 'ellas', 'nos', 'nosotros', 'vos', 'si',
#     'dentro', 'solo', 'solamente', 'saber', 'sabes', 'sabe', 'sabemos',
#     'sabeis', 'saben', 'ultimo', 'largo', 'bastante', 'haces', 'muchos',
#     'aquellos', 'aquellas', 'sus', 'entonces', 'tiempo', 'verdad', 'verdadero',
#     'verdadera', 'cierto', 'ciertos', 'cierta', 'ciertas', 'intentar', 'del',
#     'intento', 'intenta', 'intentas', 'intentamos', 'intentais', 'intentan',
#     'dos', 'bajo', 'arriba', 'encima', 'usar', 'uso', 'usas', 'usa', 'usamos',
#     'usais', 'usan', 'emplear', 'empleo', 'empleas', 'emplean', 'ampleamos',
#     'empleais', 'valor', 'muy', 'era', 'eras', 'eramos', 'eran', 'modo',
#     'bien', 'cual', 'cuando', 'donde', 'mientras', 'quien', 'con', 'entre',
#     'sin', 'trabajo', 'trabajar', 'trabajas', 'trabaja', 'trabajamos',
#     'trabajais', 'trabajan', 'podria', 'podrias', 'podriamos', 'podrian',
#     'podriais', 'yo', 'aquel', 'que', 'a', 'y', 'de', 'se'
# ]
